// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "10.0.0-alpha.2-13-g23397a2adf-dirty"
#define MICROPY_GIT_HASH "23397a2adf-dirty"
#define MICROPY_BUILD_DATE "2025-04-29"
#define MICROPY_VERSION_MAJOR (10)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (0)
#define MICROPY_VERSION_PRERELEASE 0
#define MICROPY_VERSION_STRING "10.0.0"
// Combined version as a 32-bit number for convenience
#define MICROPY_VERSION (MICROPY_VERSION_MAJOR << 16 | MICROPY_VERSION_MINOR << 8 | MICROPY_VERSION_MICRO)
#define MICROPY_FULL_VERSION_INFO "Adafruit CircuitPython " MICROPY_GIT_TAG " on " MICROPY_BUILD_DATE "; " MICROPY_BANNER_MACHINE
