// Automatically generated by make_root_pointers.py.

const char *readline_hist[(8)];
mp_obj_list_t mp_sys_argv_obj;
mp_obj_t board_uart_bus;
mp_obj_t keypad_scanners_linked_list;
mp_obj_t playing_audio[4];
mp_obj_t rtc_time_source;
mp_obj_t sys_mutable[MP_SYS_MUTABLE_NUM];
struct _mp_vfs_mount_t *vfs_cur;
struct _mp_vfs_mount_t *vfs_mount_table;
